"""
AI prompts package.
"""
from app.ai.prompts.trading import (
    TWO_MODE_SYSTEM_PROMPT,
    REASONER_SYSTEM_PROMPT,
    COMPOSER_SYSTEM_PROMPT,
    CODE_AWARE_ADVISOR_SYSTEM_PROMPT,
    ANALYST_SYSTEM_PROMPT,
    CODE_GEN_SYSTEM_PROMPT,
    CODE_EXPLAINER_SYSTEM_PROMPT,
    CLASSIFIER_SYSTEM_PROMPT,
    TOOL_CALLER_SYSTEM_PROMPT,
    STRUCTURED_OUTPUT_SYSTEM_PROMPT,
    JUDGE_SYSTEM_PROMPT_TEMPLATE,
)

__all__ = [
    "TWO_MODE_SYSTEM_PROMPT",
    "REASONER_SYSTEM_PROMPT",
    "COMPOSER_SYSTEM_PROMPT",
    "CODE_AWARE_ADVISOR_SYSTEM_PROMPT",
    "ANALYST_SYSTEM_PROMPT",
    "CODE_GEN_SYSTEM_PROMPT",
    "CODE_EXPLAINER_SYSTEM_PROMPT",
    "CLASSIFIER_SYSTEM_PROMPT",
    "TOOL_CALLER_SYSTEM_PROMPT",
    "STRUCTURED_OUTPUT_SYSTEM_PROMPT",
    "JUDGE_SYSTEM_PROMPT_TEMPLATE",
]